"""Tests for spektr.output.report -- Markdown export."""

from pathlib import Path

import pytest

from spektr.core.fetcher import CVERecord
from spektr.output.report import generate_markdown, save_report


def _make_record(**kwargs) -> CVERecord:
    defaults = {
        "id": "CVE-2021-44228",
        "description": "Apache Log4j2 RCE vulnerability",
        "cvss_v3_score": 10.0,
        "cvss_v3_severity": "CRITICAL",
        "cvss_v3_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:C/C:H/I:H/A:H",
        "epss_score": 0.975,
        "epss_percentile": 0.999,
        "published": "2021-12-10T10:15:00",
        "last_modified": "2023-11-06T21:15:00",
        "references": ["https://nvd.nist.gov/vuln/detail/CVE-2021-44228"],
        "cwe_ids": ["CWE-502"],
        "in_kev": True,
        "spektr_score": 9.8,
    }
    defaults.update(kwargs)
    return CVERecord(**defaults)


def test_generate_markdown_has_title() -> None:
    records = [_make_record()]
    md = generate_markdown("log4j", records)
    assert "# spektr report: log4j" in md


def test_generate_markdown_has_table() -> None:
    records = [_make_record()]
    md = generate_markdown("log4j", records)
    assert "| # | Severity | CVE ID |" in md
    assert "CVE-2021-44228" in md


def test_generate_markdown_has_detail_section() -> None:
    records = [_make_record()]
    md = generate_markdown("log4j", records)
    assert "## CVE-2021-44228" in md
    assert "Apache Log4j2 RCE vulnerability" in md


def test_generate_markdown_shows_cvss() -> None:
    records = [_make_record()]
    md = generate_markdown("log4j", records)
    assert "**CVSS v3**: 10.0" in md


def test_generate_markdown_shows_epss() -> None:
    records = [_make_record()]
    md = generate_markdown("log4j", records)
    assert "**EPSS**:" in md


def test_generate_markdown_shows_kev() -> None:
    records = [_make_record(in_kev=True)]
    md = generate_markdown("log4j", records)
    assert "KEV" in md
    assert "Known Exploited" in md


def test_generate_markdown_no_kev() -> None:
    records = [_make_record(in_kev=False)]
    md = generate_markdown("log4j", records)
    assert "Known Exploited" not in md


def test_generate_markdown_footer() -> None:
    records = [_make_record()]
    md = generate_markdown("log4j", records)
    assert "Generated by spektr" in md


def test_generate_markdown_multiple_records() -> None:
    records = [
        _make_record(id="CVE-2021-44228", spektr_score=9.8),
        _make_record(id="CVE-2021-45046", cvss_v3_score=9.0, spektr_score=7.6),
    ]
    md = generate_markdown("log4j", records)
    assert "CVE-2021-44228" in md
    assert "CVE-2021-45046" in md
    assert "2 CVEs found" in md


def test_generate_markdown_sorts_by_score() -> None:
    records = [
        _make_record(id="CVE-LOW", spektr_score=2.0),
        _make_record(id="CVE-HIGH", spektr_score=9.0),
    ]
    md = generate_markdown("test", records)
    # HIGH should appear before LOW in the table
    high_pos = md.index("CVE-HIGH")
    low_pos = md.index("CVE-LOW")
    assert high_pos < low_pos


def test_save_report_creates_file(tmp_path: Path) -> None:
    records = [_make_record()]
    out = tmp_path / "report.md"
    path = save_report("log4j", records, str(out))
    assert path.exists()
    content = path.read_text(encoding="utf-8")
    assert "spektr report" in content


def test_generate_markdown_no_cvss() -> None:
    records = [_make_record(cvss_v3_score=None, cvss_v3_severity=None)]
    md = generate_markdown("test", records)
    assert "CVSS v3" not in md


def test_save_report_auto_generates_filename(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.chdir(tmp_path)
    records = [_make_record()]
    path = save_report("log4j", records)
    assert path.exists()
    assert path.name.startswith("log4j_")
    assert path.suffix == ".md"


def test_save_report_overwrite_prompt_no(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.chdir(tmp_path)
    existing = tmp_path / "report.md"
    existing.write_text("old", encoding="utf-8")
    monkeypatch.setattr("builtins.input", lambda _: "n")
    records = [_make_record()]
    path = save_report("log4j", records, str(existing))
    # Should NOT overwrite, should create auto-named file instead
    assert path.name != "report.md"
    assert path.name.startswith("log4j_")
    assert existing.read_text(encoding="utf-8") == "old"


def test_save_report_overwrite_prompt_yes(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    existing = tmp_path / "report.md"
    existing.write_text("old", encoding="utf-8")
    monkeypatch.setattr("builtins.input", lambda _: "y")
    records = [_make_record()]
    path = save_report("log4j", records, str(existing))
    assert path.name == "report.md"
    assert "spektr report" in path.read_text(encoding="utf-8")


def test_generate_markdown_references() -> None:
    # 7 refs across different domains to avoid per-domain cap
    refs = [f"https://site{i}.com/advisory" for i in range(7)]
    records = [_make_record(references=refs)]
    md = generate_markdown("test", records)
    assert "https://site0.com/advisory" in md
    assert "and 2 more" in md


def test_generate_markdown_caps_refs_per_domain() -> None:
    # 6 refs from the same domain → only 3 kept (per-domain limit)
    refs = [f"https://example.com/{i}" for i in range(6)]
    records = [_make_record(references=refs)]
    md = generate_markdown("test", records)
    assert "https://example.com/0" in md
    assert "https://example.com/2" in md
    assert "https://example.com/3" not in md


def test_generate_markdown_deduplicates_references() -> None:
    refs = ["https://example.com/a", "https://example.com/a", "https://example.com/b"]
    records = [_make_record(references=refs)]
    md = generate_markdown("test", records)
    assert md.count("https://example.com/a") == 1
