"""Markdown report export for spektr results."""

from __future__ import annotations

import re
from datetime import datetime
from pathlib import Path

from spektr import __version__
from spektr.core.fetcher import CVERecord
from spektr.output.terminal import _limit_refs_per_domain
from spektr.providers.base import TriageResult


def _auto_filename(query: str) -> str:
    """Generate a filename like 'apache2_20260405_1347.md'."""
    safe = re.sub(r"[^\w\-]", "_", query.strip().lower())
    safe = re.sub(r"_+", "_", safe).strip("_")
    ts = datetime.now().strftime("%Y%m%d_%H%M")
    return f"{safe}_{ts}.md"


def _severity_label(severity: str | None) -> str:
    """Return severity with markdown emphasis."""
    label = (severity or "N/A").upper()
    if label == "CRITICAL":
        return f"**{label}**"
    if label == "HIGH":
        return f"**{label}**"
    return label


def generate_markdown(
    query: str,
    records: list[CVERecord],
    sort_by: str = "spektr_score",
    triage: TriageResult | None = None,
    triage_provider: str = "",
) -> str:
    """Generate a Markdown report string from search results."""
    sort_keys = {
        "spektr_score": lambda r: r.spektr_score,
        "cvss": lambda r: r.cvss_v3_score or 0,
        "epss": lambda r: r.epss_percentile if r.epss_percentile is not None else 0,
        "published": lambda r: r.published,
    }
    key_fn = sort_keys.get(sort_by, sort_keys["spektr_score"])
    sorted_records = sorted(records, key=key_fn, reverse=True)

    lines: list[str] = []
    lines.append(f"# spektr report: {query}")
    lines.append("")
    lines.append(f"**{len(records)} CVEs found** | sorted by {sort_by}")
    lines.append("")

    # Summary table
    lines.append("| # | Severity | CVE ID | CVSS | EPSS% | KEV | Score |")
    lines.append("|---|----------|--------|------|-------|-----|-------|")

    for i, r in enumerate(sorted_records, 1):
        sev = _severity_label(r.cvss_v3_severity)
        cvss = f"{r.cvss_v3_score:.1f}" if r.cvss_v3_score is not None else "-"
        epss = f"{r.epss_percentile * 100:.1f}" if r.epss_percentile is not None else "-"
        kev = "!!" if r.in_kev else "-"
        score = f"{r.spektr_score:.1f}"
        lines.append(f"| {i} | {sev} | {r.id} | {cvss} | {epss} | {kev} | {score} |")

    lines.append("")

    # Detail sections
    for r in sorted_records:
        lines.append(f"## {r.id}")
        lines.append("")
        lines.append(r.description)
        lines.append("")

        details: list[str] = []
        if r.cvss_v3_score is not None:
            details.append(f"- **CVSS v3**: {r.cvss_v3_score:.1f} ({r.cvss_v3_severity})")
        if r.cvss_v3_vector:
            details.append(f"- **Vector**: `{r.cvss_v3_vector}`")
        if r.epss_score is not None:
            pct = r.epss_percentile if r.epss_percentile is not None else 0
            details.append(f"- **EPSS**: {r.epss_score:.4f} (top {(1 - pct) * 100:.1f}%)")
        if r.in_kev:
            details.append("- **KEV**: In CISA Known Exploited Vulnerabilities")
        details.append(f"- **spektr score**: {r.spektr_score:.1f}/10.0")

        if r.cwe_ids:
            details.append(f"- **CWEs**: {', '.join(dict.fromkeys(r.cwe_ids))}")
        if r.published:
            details.append(f"- **Published**: {r.published[:10]}")

        lines.extend(details)
        lines.append("")

        if r.references:
            seen: set[str] = set()
            unique_refs = [ref for ref in r.references if ref not in seen and not seen.add(ref)]
            capped_refs = _limit_refs_per_domain(unique_refs)
            lines.append("**References:**")
            for ref in capped_refs[:5]:
                lines.append(f"- {ref}")
            if len(capped_refs) > 5:
                lines.append(f"- ... and {len(capped_refs) - 5} more")
            lines.append("")

    # Triage section
    if triage is not None:
        lines.append("## AI Triage")
        lines.append("")
        lines.append(f"**Summary:** {triage.summary}")
        lines.append("")
        lines.append(f"**Priority:** {', '.join(triage.prioritized)}")
        lines.append("")
        for cve_id, reason in triage.reasoning.items():
            lines.append(f"- **{cve_id}**: {reason}")
        lines.append("")
        lines.append(f"**Attack path:** {triage.attack_path}")
        lines.append("")
        lines.append("**Recommended actions:**")
        for action in triage.recommended_actions:
            lines.append(f"- {action}")
        lines.append("")
        if triage_provider:
            lines.append(f"*Triage by: {triage_provider}*")
            lines.append("")

    # Footer
    lines.append("---")
    lines.append(f"*Generated by spektr v{__version__} | Data: NVD API v2 + EPSS + KEV*")
    lines.append("")

    return "\n".join(lines)


def save_report(
    query: str,
    records: list[CVERecord],
    output_path: str | None = None,
    sort_by: str = "spektr_score",
    triage: TriageResult | None = None,
    triage_provider: str = "",
) -> Path:
    """Generate and save a Markdown report to disk."""
    content = generate_markdown(
        query, records, sort_by, triage=triage, triage_provider=triage_provider
    )

    if output_path is None:
        # No path given -- auto-generate
        path = Path(_auto_filename(query))
    else:
        path = Path(output_path).resolve()
        try:
            path.relative_to(Path.cwd().resolve())
        except ValueError as e:
            msg = f"Output path must be within the current directory. Got: {path}"
            raise ValueError(msg) from e
        original_dir = path.parent
        # Auto-append .md if no extension given
        if not path.suffix:
            path = path.with_suffix(".md")
        # Don't overwrite directories
        if path.is_dir():
            path = path / _auto_filename(query)
        # Prompt before overwriting existing files
        if path.exists():
            try:
                answer = input(f"  '{path.name}' already exists. Overwrite? [y/N] ").strip().lower()
            except EOFError:
                answer = "n"
            if answer != "y":
                path = original_dir / _auto_filename(query)
                # Ensure fallback filename is unique
                base = path.stem
                suffix = path.suffix
                counter = 2
                while path.exists():
                    path = original_dir / f"{base}_{counter}{suffix}"
                    counter += 1

    if path.exists() and path.is_symlink():
        raise ValueError(f"Refusing to write through symlink: {path}")

    path.write_text(content, encoding="utf-8")
    return path
