"""Markdown report export for spektr results."""

from __future__ import annotations

import re
from collections import Counter
from datetime import datetime
from pathlib import Path
from urllib.parse import urlparse

from spektr import __version__
from spektr.core.fetcher import CVERecord


def _limit_refs_per_domain(refs: list[str], max_per_domain: int = 3) -> list[str]:
    """Return refs with at most *max_per_domain* URLs per domain."""
    domain_count: Counter[str] = Counter()
    result: list[str] = []
    for url in refs:
        try:
            domain = urlparse(url).netloc.lower()
        except ValueError:
            domain = url
        domain_count[domain] += 1
        if domain_count[domain] <= max_per_domain:
            result.append(url)
    return result


def _auto_filename(query: str) -> str:
    """Generate a filename like 'apache2_20260405_1347.md'."""
    safe = re.sub(r"[^\w\-]", "_", query.strip().lower())
    safe = re.sub(r"_+", "_", safe).strip("_")
    ts = datetime.now().strftime("%Y%m%d_%H%M")
    return f"{safe}_{ts}.md"


def _severity_label(severity: str | None) -> str:
    """Return severity with markdown emphasis."""
    label = (severity or "N/A").upper()
    if label == "CRITICAL":
        return f"**{label}**"
    if label == "HIGH":
        return f"**{label}**"
    return label


def generate_markdown(
    query: str,
    records: list[CVERecord],
    sort_by: str = "spektr_score",
) -> str:
    """Generate a Markdown report string from search results."""
    sort_keys = {
        "spektr_score": lambda r: r.spektr_score,
        "cvss": lambda r: r.cvss_v3_score or 0,
        "epss": lambda r: r.epss_percentile or 0,
        "published": lambda r: r.published,
    }
    key_fn = sort_keys.get(sort_by, sort_keys["spektr_score"])
    sorted_records = sorted(records, key=key_fn, reverse=True)

    lines: list[str] = []
    lines.append(f"# spektr report: {query}")
    lines.append("")
    lines.append(f"**{len(records)} CVEs found** | sorted by {sort_by}")
    lines.append("")

    # Summary table
    lines.append("| # | Severity | CVE ID | CVSS | EPSS% | KEV | Score |")
    lines.append("|---|----------|--------|------|-------|-----|-------|")

    for i, r in enumerate(sorted_records, 1):
        sev = _severity_label(r.cvss_v3_severity)
        cvss = f"{r.cvss_v3_score:.1f}" if r.cvss_v3_score is not None else "-"
        epss = f"{r.epss_percentile * 100:.1f}" if r.epss_percentile else "-"
        kev = "!!" if r.in_kev else "-"
        score = f"{r.spektr_score:.1f}"
        lines.append(f"| {i} | {sev} | {r.id} | {cvss} | {epss} | {kev} | {score} |")

    lines.append("")

    # Detail sections
    for r in sorted_records:
        lines.append(f"## {r.id}")
        lines.append("")
        lines.append(r.description)
        lines.append("")

        details: list[str] = []
        if r.cvss_v3_score is not None:
            details.append(f"- **CVSS v3**: {r.cvss_v3_score:.1f} ({r.cvss_v3_severity})")
        if r.cvss_v3_vector:
            details.append(f"- **Vector**: `{r.cvss_v3_vector}`")
        if r.epss_score is not None:
            details.append(f"- **EPSS**: {r.epss_score:.4f} (top {(1 - (r.epss_percentile or 0)) * 100:.1f}%)")
        if r.in_kev:
            details.append("- **KEV**: In CISA Known Exploited Vulnerabilities")
        details.append(f"- **spektr score**: {r.spektr_score:.1f}/10.0")

        if r.cwe_ids:
            details.append(f"- **CWEs**: {', '.join(dict.fromkeys(r.cwe_ids))}")
        if r.published:
            details.append(f"- **Published**: {r.published[:10]}")

        lines.extend(details)
        lines.append("")

        if r.references:
            seen: set[str] = set()
            unique_refs = [ref for ref in r.references if ref not in seen and not seen.add(ref)]
            capped_refs = _limit_refs_per_domain(unique_refs)
            lines.append("**References:**")
            for ref in capped_refs[:5]:
                lines.append(f"- {ref}")
            if len(capped_refs) > 5:
                lines.append(f"- ... and {len(capped_refs) - 5} more")
            lines.append("")

    # Footer
    lines.append("---")
    lines.append(f"*Generated by spektr v{__version__} | Data: NVD API v2 + EPSS + KEV*")
    lines.append("")

    return "\n".join(lines)


def save_report(
    query: str,
    records: list[CVERecord],
    output_path: str | None = None,
    sort_by: str = "spektr_score",
) -> Path:
    """Generate and save a Markdown report to disk."""
    content = generate_markdown(query, records, sort_by)

    if output_path is None:
        # No path given -- auto-generate
        path = Path(_auto_filename(query))
    else:
        path = Path(output_path)
        # Auto-append .md if no extension given
        if not path.suffix:
            path = path.with_suffix(".md")
        # Don't overwrite directories
        if path.is_dir():
            path = path / _auto_filename(query)
        # Prompt before overwriting existing files
        if path.exists():
            answer = input(f"  '{path.name}' already exists. Overwrite? [y/N] ").strip().lower()
            if answer != "y":
                path = Path(_auto_filename(query))

    path.write_text(content, encoding="utf-8")
    return path
